baseURL: "https://cristianriverag.netlify.app/"
languageCode: "en-us"
title: "Cristian Rivera G."
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    - identifier: dropdown
      title: Example dropdown menu
      name: Dropdown
      weight: 3
    - identifier: dropdown1
      title: example dropdown 1
      name: example 1
      url: /#
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      title: example dropdown 2
      name: example 2
      url: /#
      parent: dropdown
      weight: 2

params:
  title: "Cristian R."
  description: Mi página personal
  # staticPath: ""  # The path to serve the static files from
  favicon: "/euler-diagram.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Cristian Rivera González" # Brand name for the brand | default is the title variable
    disableSearch: false
    searchPlaceholder: "Buscar"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: ""
    title: "¡Bienvenid@!"
    subtitle: "Gracias por visitar mi página"
    content: "Este es un espacio dedicado a explorar algunos contenidos sobre lenguajes de programación, ciencia de datos, y herramientas de uso libre que favorecen el trabajo colaborativo y el intercambio de conocimientos."
    image: /images/Captura.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Blog"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-x-twitter
          url: https://example.com
        - icon: fab fa-facebook
          url: https://example.com
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "Conóceme"
    image: "/images/microchip.png"
    content: |-
      Soy un entusiasta y aprendiz del mundo de las tecnologías de la información y las comunicaciones (TIC) con una pasión por la ciencia de datos y el desarrollo de software. 

      La curiosidad por comprender cómo las diferentes tecnologías dan forma a nuestro mundo digital, me ha llevado a dedicar tiempo y esfuerzo en el aprendizaje de algunos lenguajes de programación y áreas de la matemática.
      
      La elegancia y potencia del lenguaje [R](https://www.r-project.org/) me atraen por su aplicación en el análisis estadístico y la visualización de datos, de igual forma, me he sumergido en los múltiples usos de [Python](https://www.python.org/), aprovechando su versatilidad para interactuar con plataformas como [Arduino](https://www.arduino.cc/) y [Raspberry Pi](https://www.raspberrypi.com/) a través del desarrollo de prototipos (IoT) y sistemas automatizados con sensores de bajo costo, permitiéndome comprender los fundamentos de la electrónica, la programación y la integración entre el hardware y el software.
      
      Además, he profundizado mis conocimientos en [SQL](https://es.wikipedia.org/wiki/SQL) para gestionar bases de datos de manera efectiva y en [C++](https://isocpp.org/) para entender la lógica y la construcción de los algoritmos.
    skills:
      enable: true
      title: "Algunos de mis Intereses:"
      items:
        - "[Arduino](https://www.arduino.cc/)"
        - "Automatización"
        - "[C++](https://isocpp.org/)"
        - "Circuitos Eléctricos"
        - "Estadística"
        - "HTML"
        - "[Python](https://www.python.org/)"
        - "[R](https://www.r-project.org/)"
        - "[Raspberry Pi](https://www.raspberrypi.com/)"
        - "[SQL](https://es.wikipedia.org/wiki/SQL)"

  # Experience
  # experience:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - job: "Senior Software Developer"
  #       company: "Facebook"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2022 - present"
  #       featuredLink:
  #         enable: true
  #         name: "View the project"
  #         url: "https://example.com"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."
  # 
  #     - job: "Software Developer"
  #       company: "Amazon"
  #       companyUrl: "https://example.com"
  #       date: "Sep 2020 - Dec 2021"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       info:
  #         enable: true
  #         content: I worked as a software developer for more than one year in Amazon.
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
  # 
  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.
  # 
  #     - job: "Junior Software Developer"
  #       company: "Apple"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2020 - Aug 2020"
  #       info:
  #         enable: false
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
  # 
  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.
  # 
  #     - job: "UI/UX Designer"
  #       company: "Netflix"
  #       companyUrl: "https://example.com"
  #       date: "June 2017 - Nov 2019"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
  # 
  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.
  # 
  #     - job: "Product Designer"
  #       company: "Google"
  #       companyUrl: "https://example.com"
  #       date: "Feb 2016 - Mar 2017"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    title: "Educación"
    index: false
    items:
      - title: "Ingeniería de Control"
        school:
          name: "Universidad Nacional de Colombia, Medellín"
          url: "https://unal.edu.co/"
        #date: "2013 - 2015"
        #GPA: "3.8 out of 5.0"
        content: |-
          Cursos:
            - Geometría Vectorial y Analítica. 
            - Álgebra Lineal.
            - Cálculo Diferencial.
            - Calculo Integral.
            - Estadística.
            - Física Mecánica.
            - Electricidad y Magnetismo.
            - Análisis de Circuitos Eléctricos.
            - Instrumentación.
            
          Actividades Extracurriculares:
            - Auxiliar de Docencia Laboratorio de Geotecnia y Pavimentos.
            - Auxiliar Administrativo.
            - [Semillero en Ciencia de Datos R y Python](https://semillerorpy.netlify.app/).
      - title: "Tecnología en Análisis y Desarrollo de Software (ADSO)"
        school:
          name: "Servicio Nacional de Aprendizaje - SENA"
          url: "https://www.sena.edu.co/es-co/Paginas/default.aspx"
        date: "2023 - 2025"
        #GPA: "3.9 out of 5.0"
        content: |-
          Competencias:
          - Herramientas TIC.
          - Instrumentos de Recolección de Información.
          - Especificación Requerimientos Funcionales y no Funcionales.
          - Evaluación de Requerimientos.
          - Metodologías de Desarrollo de Software.

          Cursos Complementarios:
            - Bases de Datos: generalidades y sistemas de gestión.
            - Construcción Bases de Datos con MySQL.
            - Variables y Estructuras de Control en Python.
            - Análisis Exploratorio de Datos con Python.
            - Estructura del Lenguaje de Programación C++ (Nivel I).
        featuredLink:
          enable: true
          name: "Proyecto Página Web ADSO"
          url: "https://example.com"
      # - title: "High School"
      #   school:
      #     name: "Thomas Jefferson High School for Science and Technology."
      #     url: "https://example.org"
      #   GPA: "4.2 out of 5.0"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"

  # Achievements
  # achievements:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #       image: /images/achievment.jpg
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #       image: /images/achievment.jpg
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #       image: /images/achievment.jpg
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  # projects
  projects:
    enable: true
    title: "Proyectos"
    items:
      - title: Sitio Web ADSO 
        content: Página Web creada con Quarto para la tecnología de Análisis y Desarrollo de Software del SENA.
        image: /images/projects/sitioweb.png
        featured:
          name: Link
          link: https://riveracrist.github.io/
        badges:
          - "Quarto"
          - "Markdown"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Tablero de Datos
        content: Plantilla de un tablero de datos estático, creado con la biblioteca Flexdashboard de R.
        image: /images/projects/tablero_black.png
        featured:
          name: Link
          link: https://rpubs.com/Semilla_389/986419
        badges:
          - "Flexdashboard"
          - "Markdown"
          - "R"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Tablero de Datos con Arduino
        content: Tablero de datos que visualiza los datos capturados con sensores programados con Arduino.
        image: /images/projects/tableroarduino.png
        featured:
          name: Link
          link: https://rpubs.com/Semilla_389/1138902
        badges:
          - "Arduino"
          - "Flexdashboard"
          - "R"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2
            
      - title: R + RStudio + MySQL
        content: Documento Markdown que muestra cómo conectarse a una base de datos MySQL desde RStudio para realizar consultas y gráficos.
        image: /images/projects/rstuio_mysql.png
        featured:
          name: Link
          link: https://rpubs.com/Semilla_389/1069870
        badges:
          - "MySQL"
          - "ggplot2"
          - "Markdown"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Análisis Exploratorio Covid-19 Colombia
        content: Breve análisis descriptivo con R haciendo uso de datos abiertos del gobierno de Colombia.
        image: /images/projects/covid.png
        featured:
          name: Link
          link: https://rpubs.com/Semilla_389/691934
        badges:
          - "Arduino"
          - "Flexdashboard"
          - "R"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  # contact:
  #   enable: true
  #   title: "Contáctame"
  #   content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
  #   email: gurusabarisha@gmail.com
  #   btnName: Mail me
  #   formspree:
  #     enable: true # `contact.email` value will be ignored
  #     formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
  #     emailCaption: "Enter your email address"
  #     messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Últimas Publicaciones
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "mins. de lectura"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Leer"
    toc: "Tabla de Contenido"
    copyright: "Todos los derechos reservados"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
